#!/bin/bash
#SBATCH -J nf-ASSEMBLE_EQTL_GROUPED_ROOT
#SBATCH -o /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/3b66af31f3650124cb128ef5c22bc7/.command.log
#SBATCH --no-requeue
#SBATCH --signal B:USR2@30
#SBATCH -t 00:30:00
#SBATCH --mem 4096M
#SBATCH -p main
NXF_CHDIR=/gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/3b66af31f3650124cb128ef5c22bc7
### ---
### name: 'ASSEMBLE_EQTL_GROUPED_ROOT'
### outputs:
### - 'eqtl_grouped'
### - 'grouped_file_count.txt'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status grep -E 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | grep -E 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}

nxf_stat() {
    cpu_stat=()
    nxf_tree $1

    declare -a sum=(0 0 0 0 0 0 0 0)
    local pid
    local i
    for pid in "${!cpu_stat[@]}"; do
        local row=(${cpu_stat[pid]})
        [ $NXF_DEBUG = 1 ] && echo "++ stat mem=${row[*]}"
        for i in "${!row[@]}"; do
        if [ $i != 0 ]; then
            sum[i]=$((sum[i]+row[i]))
        fi
        done
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat SUM=${sum[*]}"

    for i in {1..7}; do
        if [ ${sum[i]} -lt ${cpu_peak[i]} ]; then
            sum[i]=${cpu_peak[i]}
        else
            cpu_peak[i]=${sum[i]}
        fi
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat PEAK=${sum[*]}\n"
    nxf_stat_ret=(${sum[*]})
}

nxf_mem_watch() {
    set -o pipefail
    local pid=$1
    local trace_file=.command.trace
    local count=0;
    declare -a cpu_stat=(0 0 0 0 0 0 0 0)
    declare -a cpu_peak=(0 0 0 0 0 0 0 0)
    local mem_tot=$(< /proc/meminfo grep MemTotal | awk '{print $2}')
    local timeout
    local DONE
    local STOP=''

    [ $NXF_DEBUG = 1 ] && nxf_sleep 0.2 && ps fx

    while true; do
        nxf_stat $pid
        if [ $count -lt 10 ]; then timeout=1;
        elif [ $count -lt 120 ]; then timeout=5;
        else timeout=30;
        fi
        read -t $timeout -r DONE || true
        [[ $DONE ]] && break
        if [ ! -e /proc/$pid ]; then
            [ ! $STOP ] && STOP=$(nxf_date)
            [ $(($(nxf_date)-STOP)) -gt 10000 ] && break
        fi
        count=$((count+1))
    done

    printf "%s\n" \
        "%mem=${nxf_stat_ret[1]}" \
        "vmem=${nxf_stat_ret[2]}" \
        "rss=${nxf_stat_ret[3]}" \
        "peak_vmem=${nxf_stat_ret[4]}" \
        "peak_rss=${nxf_stat_ret[5]}" \
        "vol_ctxt=${nxf_stat_ret[6]}" \
        "inv_ctxt=${nxf_stat_ret[7]}" >> "$trace_file" || >&2 echo "Error: Failed to append to file: $trace_file"
}

nxf_write_trace() {
    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"
}

nxf_trace_mac() {
    local start_millis=$(nxf_date)

    /bin/bash -euo pipefail /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/3b66af31f3650124cb128ef5c22bc7/.command.sh

    local end_millis=$(nxf_date)
    local wall_time=$((end_millis-start_millis))
    local ucpu=''
    local cpu_model=''
    local io_stat1=('' '' '' '' '' '')
    nxf_write_trace
}

nxf_fd() {
    local FD=11
    while [ -e /proc/$$/fd/$FD ]; do FD=$((FD+1)); done
    echo $FD
}

nxf_trace_linux() {
    local pid=$$
    command -v ps &>/dev/null || { >&2 echo "Command 'ps' required by nextflow to collect task metrics cannot be found"; exit 1; }
    local num_cpus=$(< /proc/cpuinfo grep '^processor' -c)
    local cpu_model=$(< /proc/cpuinfo grep '^model name' | head -n 1 | awk 'BEGIN{FS="\t: "} { print $2 }')
    local tot_time0=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time0=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local io_stat0=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local start_millis=$(nxf_date)
    trap 'kill $mem_proc' ERR
    
    /bin/bash -euo pipefail /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/3b66af31f3650124cb128ef5c22bc7/.command.sh &
    local task=$!

    mem_fd=$(nxf_fd)
    eval "exec $mem_fd> >(nxf_mem_watch $task)"
    local mem_proc=$!

    wait $task

    local end_millis=$(nxf_date)
    local tot_time1=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time1=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local ucpu=$(awk -v p1=$cpu_time1 -v p0=$cpu_time0 -v t1=$tot_time1 -v t0=$tot_time0 -v n=$num_cpus 'BEGIN { pct=(p1-p0)/(t1-t0)*100*n; printf("%.0f", pct>0 ? pct : 0) }' )

    local io_stat1=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local i
    for i in {0..5}; do
        io_stat1[i]=$((io_stat1[i]-io_stat0[i]))
    done

    local wall_time=$((end_millis-start_millis))
    [ $NXF_DEBUG = 1 ] && echo "+++ STATS %CPU=$ucpu TIME=$wall_time I/O=${io_stat1[*]}"

    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"

    [ -e /proc/$mem_proc ] && eval "echo 'DONE' >&$mem_fd" || true
    wait $mem_proc 2>/dev/null || true
    while [ -e /proc/$mem_proc ]; do nxf_sleep 0.1; done
}

nxf_trace() {
    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/3b66af31f3650124cb128ef5c22bc7/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -euo pipefail /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/3b66af31f3650124cb128ef5c22bc7/.command.run nxf_trace
}

nxf_stage() {
    true
    # stage input files
    rm -f chr_6
    rm -f chr_7
    rm -f chr_8
    rm -f chr_X
    rm -f chr_9
    rm -f chr_2
    rm -f chr_19
    rm -f chr_3
    rm -f chr_4
    rm -f chr_17
    rm -f chr_5
    rm -f chr_18
    rm -f chr_15
    rm -f chr_16
    rm -f chr_13
    rm -f chr_14
    rm -f chr_22
    rm -f chr_11
    rm -f chr_12
    rm -f chr_20
    rm -f chr_21
    rm -f chr_10
    rm -f chr_1
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/55/35687e88dcc09322aaea33e8a512ce/chr_6 chr_6
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/61/673452a9287c7706af5519b6f0dc33/chr_7 chr_7
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/ea/577196791910f2ce3bcb82882dcdab/chr_8 chr_8
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/1e/2bb7aa354f7c2204f02b3132631b20/chr_X chr_X
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/ba/28b0cc757348784f8aebd3ddf21898/chr_9 chr_9
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/7b/2ef5d7f21931a0fadccc593ceca14a/chr_2 chr_2
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/52/2ca9c3def31db07864224d87287b1b/chr_19 chr_19
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/31/bfdbb271158e1603fbb8d5860b82d8/chr_3 chr_3
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/a4/6ecdb5584af7d66519a9588fc10a17/chr_4 chr_4
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/30/29152fba592f6eb72452d25a98d3fa/chr_17 chr_17
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/58/ffa826cf94a724d734d39bd6f5ea34/chr_5 chr_5
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/4f/d4f91d44ea6dfa27500cc676f8d462/chr_18 chr_18
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/73/9c31726ce1ae735cbe5985c30632d1/chr_15 chr_15
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/e3/cbf433be835d93f90b70488a372b82/chr_16 chr_16
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/cc/d649cbc08d0ec1092f269f791e3a10/chr_13 chr_13
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/a4/86e482ac0fab3cb992cf15bab7711b/chr_14 chr_14
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/fb/a59c61c7ccca52173c0b23bcaefa72/chr_22 chr_22
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/92/902524c133602cdf52751f2f8125db/chr_11 chr_11
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/e491e8099c840a7ea6b2b8f10d9e82/chr_12 chr_12
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/00/5ef68605c9af19cd13f3d21a2339e1/chr_20 chr_20
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/85/e9862149198c9c9d5adb995512ce62/chr_21 chr_21
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/92/ddca1f87933049f48a8943db9967ad/chr_10 chr_10
    ln -s /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/18/664775b81e2dddd2e3c493b1d3397e/chr_1 chr_1
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /gpfs/helios/home/jaanotte/gpu-coloc-workflow-portable/work_adipoexpress_eqtl/71/3b66af31f3650124cb128ef5c22bc7/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
